### ISSUE TITLE
Periodically trying to send calls to the contract 0xAf379C844f87A7b47EE6fe5E4a9720988EaEA0AF 

### ISSUE THREAD

**Issue by yanis7774** [joshstevens19/simple-pancakeswap-sdk#1]
![Снимок экрана 2021-07-07 в 12 21 50](https://user-images.githubusercontent.com/34626980/124734642-fd33ad00-df1d-11eb-8356-9f7b905fe4a0.png)

**Comment by joshstevens19** [comment]
can you show me the swap code your trying to do please

**Comment by yanis7774** [comment]
`export` async function pancakeSwapSimple(asset, assetOne, buyAmount) {
  try {
    const fromTokenContractAddress = asset.id
    const toTokenContractAddress = assetOne.id

    const pancakeswapPair = new PancakeswapPair({
      fromTokenContractAddress: fromTokenContractAddress,
      toTokenContractAddress: toTokenContractAddress,
      ethereumAddress: ethereumAddress,
    })

    const pancakeswapPairFactory = await pancakeswapPair.createFactory()
    const trade = await pancakeswapPairFactory.trade(buyAmount.toString())
    trade.quoteChanged$.subscribe((value: TradeContext) => {

    })
    
    const price = buyAmount / trade.expectedConvertQuote

    if (assetOne.symbol === 'USDC') {
      const priceUsd = Number(trade.expectedConvertQuote).toFixed(2)
      // trade.destroy()
      return priceUsd
    }
    // trade.destroy()
    return price

  } catch (e) {
    console.log('PancakeErrorTrade', e)
  }
}
`

@joshstevens19 
I even did not do any swap. I assume this happens when trade.destroy() is commented. But not sure. Can not catch the moment it's happens.

**Comment by yanis7774** [comment]
@joshstevens19 Any update?

**Comment by joshstevens19** [comment]
I am on vacation till next Monday will look once back from holidays. Sorry about the delay.

**Comment by joshstevens19** [comment]
Hey sorry just getting round to looking at this can you tell me your `fromTokenContractAddress` and `toTokenContractAddress` is which causes this to fail also your `ethereumAddress` so I can recreate this. I can not recreate this locally so I think it could be your parameters. Thanks @yanis7774

**Comment by joshstevens19** [comment]
Inactivity will reopen once I get the details I need to recreate! Thanks
