### ISSUE TITLE
request: swap with own router

### ISSUE THREAD

**Issue by mburger81** [joshstevens19/simple-pancakeswap-sdk#6]
Hello, is it possibile with this lib to make a swap using our own Contract to get fees?

I mean actually we are using just web3.js and do something like that
```
const contract = new this.web3.eth.Contract(abi, '0x0........80');
contract.methods.swap..........
```
How can we replicate this?
thx
@joshstevens19

**Comment by joshstevens19** [comment]
Simple uniswap sdk already supports forks it’s just not documented too well example how to use here

https://github.com/Anish-Agnihotri/pool-sniper/blob/master/src/sniper.ts#L75

This package is not supported and people should use the simple uniswap sdk instead. Il comment on these packages to state this and improve the docs! Thanks for this
