### ISSUE TITLE
Request: support for TradeDirection

### ISSUE THREAD

**Issue by angrypanda0** [joshstevens19/simple-pancakeswap-sdk#8]
`simple-uniswap-sdk` has support for TradeDirection, to request quotes for desired input & output amounts. Can this be added to to `simple-pancakeswap-sdk`?

**Comment by joshstevens19** [comment]
Simple uniswap sdk already supports forks it’s just not documented too well example how to use here

https://github.com/Anish-Agnihotri/pool-sniper/blob/master/src/sniper.ts#L75

This package is not supported and people should use the simple uniswap sdk instead. Il comment on these packages to state this and improve the docs! Thanks for this
